name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential cmake git libpoco-dev

    - name: Install Eigen3
      run: |
        git clone https://github.com/eigenteam/eigen-git-mirror.git
        cd eigen-git-mirror
        git checkout 3.3.7
        mkdir build && cd build
        cmake ..
        sudo make install

    - name: Install libfranka
      run: |
        git clone --recursive https://github.com/frankaemika/libfranka.git
        cd libfranka
        git checkout 0.9.0
        git submodule update
        mkdir build && cd build
        cmake -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF ..
        make -j2
        sudo make install

    - name: Install pybind11
      run: |
        git clone https://github.com/pybind/pybind11.git
        cd pybind11
        git checkout v2.9.1
        mkdir build && cd build
        cmake -DPYBIND11_TEST=OFF ..
        make -j2
        sudo make install

    - name: Install Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        git checkout v2.13.0
        mkdir build && cd build
        cmake -DCATCH_BUILD_TESTING=OFF -DCATCH_ENABLE_WERROR=OFF -DCATCH_INSTALL_DOCS=OFF -DCATCH_INSTALL_HELPERS=OFF ..
        sudo make install

    - name: Configure & make
      run: |
        mkdir build && cd build
        cmake ..
        make -j2

    - name: Test
      run: make test
